development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: mypostgres
  database: practice
#  schema_search_path: "sample_app2"

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username: northfox
  database: northfox

cucumber:
  <<: *test